<?php 

	require_once dirname (__FILE__) . '/FeedsPlusHTTPFetcher.inc';

	function feeds_plus_feeds_plugins ()
	{
		$info = array();
		
		$info ['HTTP Fetcher (Feeds Plus)'] = array
		(
			'name'				=> 'HTTP Fetcher (Feeds Plus)',
			'description'	=> 'Download content from a URL. Enables the POST-type fetches.',
			'handler'			=> array
			(
				'parent'		=> 'FeedsFetcher',
				'class'			=> 'FeedsPlusHTTPFetcher',
				'file'			=> 'FeedsPlusHTTPFetcher.inc',
				'path'			=> drupal_get_path ('module', 'feeds_plus') . '/'
			),
		);
		return $info;
	}

	function feeds_plus_enable ()
	{
		cache_clear_all ('plugins:feeds:plugins', 'cache');
	}

?>